### ISSUE TITLE
Miotsukushi Omote development

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#51]
These assets are needed to play Miotsukushi Omote in its current untranslated state.  For testing purposes only.  This is not release-ready!

- [BGM](https://www.mediafire.com/file/icc6opsct08a61o/BGM.7z/file)
- [CG](https://www.mediafire.com/file/ota9ofzdoqp3boc/CG.7z/file)
- [movies](https://www.mediafire.com/file/pov0v5nfrqjtdks/movies.7z/file)
- [voice](https://www.mediafire.com/file/f2qcpvi32dpekiq/voice.7z/file) (or just add s14 folder to existing voices archive)
- All the scripts and json files in the higurashi-console-arcs repo on GitHub
- The latest Assembly-CSharp.dll from the higurashi-assembly repo
- (no changes necessary to the SE folder)

**Comment by DoctorDiablo** [comment]
Translation is complete!  I'll use this issue to track all the things that need to be done before release 

- [ ] Scripts need to run through the compiler for ADV/lipsync/etc support
- [ ] Scripts need to be tweaked to use the in-engine weather variants (issue #52)
- [ ] Scripts need to be tweaked to allow the use of MG and Ryukishi sprites in Taraimawashi, Tsukiotoshi, and Miotsukushi Omote (issue #21)
- [ ] Graphics archives need to be assembled for the MG and Ryukishi sprite variants
- [ ] The font glyph in the UI needs to be updated to add any unique kanji introduced in this arc, to fix the red X problem (not sure if this is necessary?)
- [ ] All the editing and translation fixes from Darbury and Meera should be packaged into the release
- [ ] Merge in all outstanding pull requests
- [ ] Miotsukushi Omote text needs to go through editing
- [ ] Investigate a method of highlighting correct choices in-game, or giving the user a method to skip them if they don't like choices (not required, but would be nice)
- [ ] Investigate putting together a PC version BGM/SE option (issue #47) (not required, but would be nice)

**Comment by enumag** [comment]
@DoctorDiablo First two items on your checklist should be fixed by #51. Please don't squash this PR when merging.

**Comment by enumag** [comment]
Here are the scripts to generate new sprites pack and voice pack. @ItaloKnox will know what to do with these.

Warning: there are a LOT of voices in the console arcs so generating the voice pack will require a lot of time and space.

[sprites-and-voices.zip](https://github.com/07th-mod/higurashi-console-arcs/files/4118612/sprites-and-voices.zip)

**Comment by enumag** [comment]
>  Scripts need to be tweaked to allow the use of MG and Ryukishi sprites in Taraimawashi, Tsukiotoshi, and Miotsukushi Omote (issue #21)

Scripts actually don't need any changes. We just need the images.

**Comment by ItaloKnox** [comment]
Here are the new packs:
[ConsoleArcs-Voices.7z](https://07th-mod.com/rikachama/temp/ConsoleArcs-Voices.7z)
[ConsoleArcs-CG.7z](https://07th-mod.com/rikachama/temp/ConsoleArcs-CG.7z)

@DoctorDiablo I need you to take a look at the errors below. I talked to enumag about them and he couldn't find the files either.

```
cp: cannot stat 'voice/ps3/s16/46/ds43020256.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020256.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/46/ds43020271.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020271.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/46/ds43020275.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020275.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/46/ds43020282.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020282.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/46/ds43020291.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020291.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/46/ds43020299.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/46/ds43020299.txt': No such file or directory
cp: cannot stat 'voice/ps3/s16/00/ds43050275.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s16/00/ds43050275.txt': No such file or directory
cp: cannot stat 'voice/ps3/s14/35/vt4bb_nagisa1008.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s14/35/vt4bb_nagisa1008.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400001.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400001.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400002.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400002.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400137.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400137.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400141.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400141.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400146.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400146.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400244.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400244.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400281.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400281.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400336.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400336.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400491.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400491.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400549.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400549.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400550.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400550.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400560.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400560.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400561.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400561.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400674.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400674.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400675.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400675.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400683.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400683.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400685.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400685.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/44/410500013.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/44/410500013.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400341.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400341.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400516.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400516.txt': No such file or directory
cp: cannot stat 'voice/ps3/s10/43/410400526.ogg': No such file or directory
cp: cannot stat 'spectrum/ps3/s10/43/410400526.txt': No such file or directory
```

**Comment by DoctorDiablo** [comment]
Hah, so this is actually pretty funny.  Turns out all of those missing files are just characters saying "..."  I guess they decided the audio files were just a waste of space and didn't put them on the disk?

![image](https://user-images.githubusercontent.com/20390474/73227023-17216b80-4140-11ea-8442-dc825c379a15.png)

**Comment by ItaloKnox** [comment]
That seems weird because we don't have such cases in the main arcs. All ellipses are actually voiced.

Maybe it's worth checking the Switch audio to see if they are there? I think we have it under the archives folder in the server.

**Comment by enumag** [comment]
I already searched my own switch audio directory while we chatted about this on Discord. But it seems the one I have is incomplete - it doesn't have these, nor the surrounding files that definitely do exist. If you have a complete Switch voices archive, please send a link.

**Comment by ItaloKnox** [comment]
Here you go, it should be [here](http://07th-mod.com/archive/HigurashiSwitch-Voices.zip).

**Comment by DoctorDiablo** [comment]
Nope, Switch audio is missing those files too.  It has all the files around them, but not these specific ones.  Guess we'll just have to live without them.

**Comment by DoctorDiablo** [comment]
@Darbury I wrote up a description so you can create the chapter select screen:

[MioOmoteDescription.txt](https://github.com/07th-mod/higurashi-console-arcs/files/4131476/MioOmoteDescription.txt)

And if you're interested, there's one more thing you can do for me.  I need to create the tips unlocked screens for this chapter.  You should be able to find the text for the tips in the tips.json file.

**Comment by Darbury** [comment]
Great, @DoctorDiablo — working on those graphics now.

Should also be done with initial proofing of all scripts by tonight. Just three more scripts to go, then I'll commit them all.

**Comment by DoctorDiablo** [comment]
Released
