### ISSUE TITLE
Miotsukushi Ura develpment

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-console-arcs#95]
Miotsukushi Ura is technically playable in its current state (in Japanese only), provided you do some nonstandard setup.  Files are posted here for backup purposes and for anyone interested in playing it in Japanese.

Install the latest console arcs release and then drop the following files on top of it:
- [CG archive](https://www.mediafire.com/file/nhx8fhi9jjg21hi/ConsoleArcs-CG-Ura.7z/file) needs to be extracted inside the \SharedAssets\CG folder
- [voices archive](https://www.mediafire.com/file/5lsbqi2meqy64h8/ConsoleArcs-voice-Ura.7z/file) needs to be extracted inside the \SharedAssets\SE folder (yes SE, not voices)
- [new script files](https://www.mediafire.com/file/nynzynj4y9oby6a/ConsoleArcs-Update-Ura.7z/file) (needs to be extracted inside the \SharedAssets\Update folder)

A handful of things won't work correctly (no lipsync, nametags won't be visible) because those steps are implemented after translation is complete, and there are a few things I forgot to do (like fixing the chapter select screen) but it should be playable all the way to the end of the arc.

**Comment by DoctorDiablo** [comment]
Miotsukushi Ura translation is complete.  The following tasks still need to be done before release:

- [ ] ura_ and kake_ scripts need to run through the compiler for ADV/lipsync/etc support @enumag 
- [ ] The font glyph in the UI needs to be updated to add any unique kanji introduced in the ura_ and kake_ scripts, to fix the red X problem @tellowkrinkle 
- [ ] Create scenario preview screens for Ura and Connecting Fragments @Darbury 
- [ ] Update older scenario preview screens to be consistent with the new flowchart @Darbury 
- [ ] Investigate porting over the Matsuribayashi fragments functionality so that the Connecting Fragments can behave the same way (right now they're just implemented as tips) @DoctorDiablo but I might need some help from @tellowkrinkle / @idealpersona 
- [ ] Update lower quality Ryukishi sprites from old Hou release with cleaner versions from repo @DoctorDiablo 
- [ ] Add Okonogi MG sprites @DoctorDiablo 
- [ ] Replace 720p sprites with 1080p variants from repo @DoctorDiablo 
- [ ] Fix the window opacity bug the same way it was fixed in the main arcs @DoctorDiablo 
- [ ] Investigate putting together a PC version BGM/SE option (issue #47) @DoctorDiablo 
- [ ] Fix sprites using improper filter in rainy scenes (issue #67) @DoctorDiablo 
- [ ] Synchronize Miotsukushi Omote translation to be the same as identical scenes in Matsuribayashi (issue #175) @DoctorDiablo 
- [ ] Miotsukushi Ura and Connecting Fragments text needs to go through editing @DoctorDiablo

**Comment by enumag** [comment]
@DoctorDiablo Alternative to porting over Matsu's fragments could be to change base game for console arcs from Hima tu Matsu.

**Comment by DoctorDiablo** [comment]
Released.
